# permissions for end users to edit beaks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: beak-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: conditions-array-play
    app.kubernetes.io/part-of: conditions-array-play
    app.kubernetes.io/managed-by: kustomize
  name: beak-editor-role
rules:
- apiGroups:
  - dino.hpe.com
  resources:
  - beaks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dino.hpe.com
  resources:
  - beaks/status
  verbs:
  - get
